# Generated by Django 5.2.1 on 2025-05-20 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_header_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=20, unique=True)),
                ('profile_name', models.CharField(max_length=100)),
                ('pro_form_ids', models.JSONField(blank=True, default=list)),
                ('pro_process_ids', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueIdHeaderAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('id_for', models.CharField(max_length=50)),
                ('prefix', models.CharField(max_length=20)),
                ('last_id', models.CharField(max_length=15)),
                ('created_on', models.DateTimeField()),
                ('modified_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User_header_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('line_no', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(blank=True, max_length=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_assignments', to='accounts.profile_header_all')),
            ],
            options={
                'unique_together': {('user_id', 'line_no')},
            },
        ),
    ]
