# Generated by Django 5.2.1 on 2025-05-27 12:09

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_header_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=20, unique=True)),
                ('profile_name', models.CharField(max_length=100)),
                ('pro_form_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, help_text="List of accessible Form IDs like ['F_MAN_001', 'F_MAIN_002']", size=None)),
                ('pro_process_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list, help_text="List of accessible Process IDs like ['P_MAN_0001', 'P_DOC_0002']", size=None)),
                ('p_status', models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('p_inserted_on', models.DateTimeField(blank=True, null=True)),
                ('p_deactivated_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueIdHeaderAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('id_for', models.CharField(max_length=50)),
                ('prefix', models.CharField(max_length=20)),
                ('last_id', models.CharField(max_length=15)),
                ('created_on', models.DateTimeField()),
                ('modified_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User_header_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('line_no', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('mobile_no', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits and start with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_assignments', to='accounts.profile_header_all')),
            ],
            options={
                'unique_together': {('user_id', 'line_no')},
            },
        ),
    ]
