# Generated by Django 5.2.1 on 2025-05-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_header_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=20, unique=True)),
                ('profile_name', models.CharField(max_length=100)),
                ('pro_form_ids', models.JSONField(blank=True, default=list)),
                ('pro_process_ids', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_header_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('profile_assignments', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
