# Generated by Django 5.2.1 on 2025-05-19 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_header_all',
            name='modified_on',
        ),
    ]
