# Generated by Django 5.2.1 on 2025-05-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_header_all',
            name='profile_id',
            field=models.CharField(max_length=20),
        ),
    ]
