# Generated by Django 5.2.1 on 2025-05-19 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_header_all',
            name='profile_assignments',
        ),
        migrations.CreateModel(
            name='UserProfileAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile_header_all')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_assignments', to='accounts.user_header_all')),
            ],
            options={
                'ordering': ['line_no'],
                'unique_together': {('user', 'line_no'), ('user', 'profile')},
            },
        ),
        migrations.AddField(
            model_name='user_header_all',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='users', through='accounts.UserProfileAssignment', to='accounts.profile_header_all'),
        ),
    ]
