# Generated by Django 5.2.1 on 2025-05-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_header_all',
            name='project_id',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
