# Generated by Django 5.2.1 on 2025-05-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_header_all',
            name='is_active',
        ),
        migrations.AddField(
            model_name='profile_header_all',
            name='p_status',
            field=models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
    ]
